"""
Tests for the .dbg oracle against the synthetic test_repo fixture.

The fixture is regenerated by tools/regen_fixtures.sh; these tests assert that
parsing the fixture's .dbg file yields the symbols and locations we expect
based on the source files in tests/fixtures/test_repo/src/.

Re-run the fixture build if the source corpus changes:
    bash packages/ca65-ls/tools/regen_fixtures.sh
"""

from __future__ import annotations

from pathlib import Path

import pytest

from ca65_ls.index.dbg_oracle import SymbolRecord, build_index, load, parse_dbg


FIXTURE_DIR = Path(__file__).parent / "fixtures" / "test_repo"
DBG_PATH = FIXTURE_DIR / "build" / "test_repo.dbg"


@pytest.fixture(scope="module")
def index():
    if not DBG_PATH.exists():
        pytest.skip(
            f"{DBG_PATH} not built; run tools/regen_fixtures.sh first."
        )
    return load(DBG_PATH)


def _only(records: list[SymbolRecord]) -> SymbolRecord:
    """Assert that a lookup returned exactly one record and return it."""
    assert len(records) == 1, f"expected 1 record, got {len(records)}: {records}"
    return records[0]


def _only_def(records: list[SymbolRecord]) -> SymbolRecord:
    """Filter to the (single) defining-side record, ignoring `type=imp` references."""
    defs = [r for r in records if r.kind != "import"]
    assert len(defs) == 1, f"expected 1 defining record, got {len(defs)}: {defs}"
    return defs[0]


# ------------------------------------------------- basic parse / record-shape


def test_parse_records_present(index):
    """The header records are parsed and have plausible counts."""
    assert "version" in index.raw
    assert index.raw["version"][0]["major"] == 2
    info = index.raw["info"][0]
    assert info["file"] == len(index.raw["file"])
    assert info["mod"] == len(index.raw["mod"])
    assert info["scope"] == len(index.raw["scope"])
    assert info["sym"] == len(index.raw["sym"])
    assert info["seg"] == len(index.raw["seg"])


def test_known_files_present(index):
    """All four source files plus zp.inc appear in the file table."""
    file_paths = set(index.files.values())
    assert {"src/zp.s", "src/lib.s", "src/helpers.s", "src/main.s", "inc/zp.inc"} <= file_paths


# ------------------------------------------------- module-level export symbols


def test_lib_export_is_label_in_lib_s(index):
    rec = _only_def(index.lookup("lib_export"))
    assert rec.kind == "label"
    assert rec.file == "src/lib.s"
    assert rec.segment == "CODE"
    assert rec.addr is not None and rec.addr >= 0x800
    # We don't pin the exact line because comment edits in lib.s shouldn't
    # break the test; just assert it points somewhere inside lib.s body.
    assert rec.line is not None and 1 <= rec.line <= 100


def test_lib_const_is_absolute_label(index):
    """`.export lib_const := $1234` is recorded by cc65 as type=lab (an absolute-
    address label), not type=equ. The distinguishing feature is the absence of
    a segment association combined with the resolved val=."""
    rec = _only_def(index.lookup("lib_const"))
    assert rec.kind == "label"
    assert rec.segment is None  # no segment -> it's a pure address constant
    assert rec.addr == 0x1234


def test_lib_buffer_in_bss(index):
    rec = _only_def(index.lookup("lib_buffer"))
    assert rec.kind == "label"
    assert rec.segment == "BSS"


# -------------------------------------------------- zeropage + globalzp symbols


def test_ptr1_is_zeropage_at_address_2(index):
    recs = index.lookup("ptr1")
    # ptr1 appears as a label in zp.s and as imports in lib.s/helpers.s/main.s
    label_recs = [r for r in recs if r.kind == "label"]
    rec = _only(label_recs)
    assert rec.addrsize == "zeropage"
    assert rec.addr == 0x02
    assert rec.segment == "ZEROPAGE"


# ------------------------------------------------- scope-resolved symbols


def test_helpers_foo_has_scope_path(index):
    """`foo` is defined inside `.scope helpers` and should have scope_path ('helpers',)."""
    foos = [r for r in index.lookup("foo") if r.kind == "label"]
    assert len(foos) >= 1
    rec = foos[0]
    assert rec.scope_path == ("helpers",), f"scope_path={rec.scope_path}"
    assert rec.file == "src/helpers.s"


def test_helpers_bar_has_scope_path(index):
    bars = [r for r in index.lookup("bar") if r.kind == "label"]
    assert len(bars) >= 1
    rec = bars[0]
    assert rec.scope_path == ("helpers",)


def test_helpers_foo_alias_exports_to_module_scope(index):
    """The `.export helpers_foo := helpers::foo` alias appears at module scope."""
    rec = _only_def(index.lookup("helpers_foo"))
    assert rec.kind == "label"
    # alias is defined at the module-level scope of helpers.s, so scope_path is empty
    assert rec.scope_path == ()
    assert rec.file == "src/helpers.s"
    foo_def = next(r for r in index.lookup("foo") if r.kind == "label")
    assert rec.addr == foo_def.addr  # same address as the aliased target


# ------------------------------------------------- struct field symbols


def test_struct_S_fields_are_equs_with_scope(index):
    """`flags` and `count` are field-offset equs inside .struct S."""
    flags = _only(index.lookup("flags"))
    assert flags.kind == "equ"
    assert flags.scope_path == ("S",)
    assert flags.addr == 0  # first field

    count = _only(index.lookup("count"))
    assert count.kind == "equ"
    assert count.scope_path == ("S",)
    assert count.addr == 1  # offset after the 1-byte `flags`


# ------------------------------------------------- cheap locals


def test_cheap_local_inner_appears_twice_with_distinct_parents(index):
    """`@inner` is defined in both `foo` and `bar` and should be distinguishable
    by the parent_name field."""
    inners = index.lookup("@inner")
    assert len(inners) == 2, f"expected 2 @inner records, got {len(inners)}"
    parents = {r.parent_name for r in inners}
    assert parents == {"foo", "bar"}


def test_cheap_local_retry_in_start(index):
    """`@retry` in _start should have _start as parent."""
    retries = index.lookup("@retry")
    assert len(retries) == 1
    assert retries[0].parent_name == "_start"


# ------------------------------------------------- imports / cross-module


def test_main_imports_resolve_to_their_exporters(index):
    """In main.s, `.import lib_export` should appear as a type=import record
    whose import_of points back to lib.s's `lib_export` label."""
    imports = [r for r in index.lookup("lib_export") if r.kind == "import"]
    assert len(imports) == 1
    assert imports[0].import_of == "lib_export"
    assert imports[0].file == "src/main.s"


# --------------------------------------------------------- oracle smoke / CLI


def test_oracle_finds_every_declared_export():
    """≥95% oracle coverage: every name in tests/fixtures/test_repo/build/test_repo.lbl
    that isn't a linker-generated `__FOO__` symbol must be in our index."""
    if not DBG_PATH.exists():
        pytest.skip("fixtures not built")
    idx = load(DBG_PATH)
    lbl_path = FIXTURE_DIR / "build" / "test_repo.lbl"
    expected: set[str] = set()
    for line in lbl_path.read_text().splitlines():
        parts = line.split()
        if len(parts) < 3:
            continue
        name = parts[2].lstrip(".")
        if name.startswith("__") and name.endswith("__"):
            continue  # linker-internal
        expected.add(name)
    missing = {n for n in expected if not idx.lookup(n)}
    coverage = (len(expected) - len(missing)) / len(expected) if expected else 1.0
    assert coverage >= 0.95, f"coverage={coverage:.2%}, missing={missing}"
